export type CRUD_ModalsType =
  | "brands"
  | "contracts"
  | "services"
  | "discrepancies"
  | "roadmaps"
  | "drivers"
  | "cars"
  | "couples"
  | "districts"
  | "fuels"
  | "countries"
  | "tour_groups"
  | "reports"
  | "roles"
  | "users";
